### ISSUE TITLE
Size and type of readed structure

### ISSUE THREAD

**Issue by oocanto** [UnknownUser95/Java-EventReader#1]
Could you please explain how can you read [24 bytes](https://github.com/UnknownUser95/Java-EventReader/blob/4ea0c14481c6b2b3c585f2ae4a5fc92406372ef4/src/main/java/net/unknownuser/eventreader/EventReader.java#L99) from input device, since in [this post](https://stackoverflow.com/a/3877020) it is supposed that the input struct only has 16 bytes? Or am I misunderstanding the concept?

Great work!

Thank you in advance.

**Comment by Callisto95** [comment]
Because I would forget myself, I have written down the length of everything at the [InputEvent](https://github.com/UnknownUser95/Java-EventReader/blob/4ea0c14481c6b2b3c585f2ae4a5fc92406372ef4/src/main/java/net/unknownuser/eventreader/InputEvent.java#L8) record.

I have tested what the command mentioned in the post and the value is not in the same spot every time. They used the wrong amount of bytes per line (to properly see the input event). Modifying it to use 24 bytes (`od -tx1 -w24 /dev/input/by-path/pci-0000:09:00.3-usb-0:5:1.0-event-mouse` for my mouse!) always puts the value in the same spot.

**Comment by Callisto95** [comment]
I have now made it clearer. Instead of just using the magic number 24, [it's now composed of the byte amount of the individual parts](https://github.com/UnknownUser95/Java-EventReader/blob/1b545a40f04a87b686308fe5e4074506851a56fa/src/main/java/net/unknownuser/eventreader/InputEvent.java#L13).

**Comment by oocanto** [comment]
Sorry, but I do not think I made myself understood correctly. What I am pointing out is that the 24 bytes structure does not seem to be correct, because in the official documentation the structure has only 16 bytes: 8 for a time tag, 2 for the event type, 2 for the code and 4 for the raw value.

In total, there are 16 bytes that can be seen from this struct. This is defined in /usr/include/linux/input.h

<pre>
struct input_event {
 struct timeval time; // 8 bytes
 __u16 type;          // 2 bytes
 __u16 code;          // 2 bytes
 __s32 value;         // 4 bytes
};
</pre>

That is just the confusion.

I hope it does not result in more confusion or inconvenience for you.

Thank you very much.

Kind regards.

**Comment by Callisto95** [comment]
I see what you mean.

The timeval struct has two 8 byte long's (although not of type long, but time_t and suseconds_t).
